
skillMetadata:
  sections:
    - name: Credentials
      fields:
        - type: label
          label: You can specify the access settings of your Bring! account here (comfortable) or locally in the skill directory via credentials.py (secure)
        - name: login
          type: text
          label: Your login/email
          value: ""
        - name: password
          type: password
          label: Your password
          value: ""
